title: Hades Research
#logo: /assets/img/headshot_circle.png
#description: text below image
#show_downloads: true

#author:
 # name: Ajax
 # email: your-email@gmail.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  This a blog space and knowledge sharing platform where we can interact and share
  our cyber security research. Here we constantly learn and grow with Malware analysis
  and APT-simulation based resarch.

# Build settings

# If you clone the Minima repo and build locally, use this setting.
theme: jekyll-theme-hacker

# As of November 2023, GitHub Pages still uses Minima 2.5.1 (https://pages.github.com/versions/). 
# If you want to use the latest Minima version on GitHub Pages, use the following setting and 
# add a line comment on "theme: minima" above.
#remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/anubhav-patel/" }
